; ============================================================
; Tasmota для Freenove ESP32-S3 WROOM (N16R8) + камера OV3660
; Скопіюйте цей файл у корінь папки Tasmota як platformio_override.ini
; ============================================================

[platformio]
default_envs = tasmota32s3-webcam-ov3660

[env:tasmota32s3-webcam-ov3660]
extends = env:tasmota32_base
board = freenove_esp32s3_n16r8
board_build.f_cpu = 240000000L
build_flags =
  ${env:tasmota32_base.build_flags}
  -DFIRMWARE_WEBCAM
  -DCAMERA_MODEL_FREENOVE_ESP32S3
  -DUSE_WEBCAM_V2
  -DBOARD_HAS_PSRAM
  -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32-webcam.bin"'
lib_extra_dirs = lib/lib_ssl, lib/libesp32
