; platformio_tasmota_cenv.ini - Freenove ESP32-S3 N16R8 + OV3660

[env:tasmota32s3-webcam-ov3660]
extends = env:tasmota32s3
board = freenove_esp32s3_n16r8

board_build.partitions = partitions_16mb.csv

build_flags = ${env:tasmota32s3.build_flags}
    -DFIRMWARE_WEBCAM
    -DUSE_WEBCAM
    -DCODE_IMAGE_STR="\"webcam-ov3660\""
    -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32s3-webcam.bin"'
    -DUSE_LVGL=0
    -DUSE_DISPLAY=0
    -DUSE_HASPMOTA=0

lib_extra_dirs = ${env:tasmota32s3.lib_extra_dirs}
    lib/lib_ssl

lib_ignore = ${env:tasmota32s3.lib_ignore}
    lvgl
    HASPmota
    Berry mapping to LVGL
    LVGL_assets
    Display renderer
    universal display Library
